#include "ScriptCompiler.h"
#include "engine/core/Logger.h"
#include "engine/platform/PlatformUtils.h"

#include <fstream>
#include <sstream>
#include <filesystem>
#include <cstdlib>
#include <vector>

namespace fs = std::filesystem;

namespace editor {

static constexpr uint32_t SUBPROCESS_TIMEOUT_MS = 120000;

ScriptCompiler::ScriptCompiler()
    : m_process_runner(engine::platform::create_process_runner())
{
}

ScriptCompiler::~ScriptCompiler() {
    if (m_build_future.valid()) {
        m_build_future.wait();
    }
}

void ScriptCompiler::set_project_path(const std::string& path) {
    m_project_path = path;
    m_scripts_path = (fs::path(path) / "Scripts").string();
    m_build_path = (fs::path(path) / "Library" / "ScriptBuild").string();
}

void ScriptCompiler::set_engine_include_path(const std::string& path) {
    m_engine_include_path = path;
}

void ScriptCompiler::set_engine_build_path(const std::string& path) {
    m_engine_build_path = path;
}

std::string ScriptCompiler::dll_path() const {
    return (fs::path(m_project_path) / "Library" / "ScriptAssemblies" /
            engine::platform::shared_library_name("GameScripts")).string();
}

bool ScriptCompiler::generate_cmake() {
    if (m_project_path.empty() || m_engine_include_path.empty()) {
        m_last_error = "Project path or engine include path not set";
        return false;
    }

    // Create Scripts directory (for CMakeLists.txt and ScriptRegistry.cpp)
    fs::create_directories(m_scripts_path);

    // Generate CMakeLists.txt
    std::string cmake_path = (fs::path(m_scripts_path) / "CMakeLists.txt").string();
    std::ofstream cmake_file(cmake_path);

    if (!cmake_file.is_open()) {
        m_last_error = "Failed to create CMakeLists.txt";
        return false;
    }

    // Convert paths to use forward slashes for CMake
    std::string engine_include = m_engine_include_path;
    std::replace(engine_include.begin(), engine_include.end(), '\\', '/');

    std::string engine_build = m_engine_build_path;
    std::replace(engine_build.begin(), engine_build.end(), '\\', '/');

    cmake_file << R"(# Auto-generated by Eruption Editor - DO NOT EDIT
cmake_minimum_required(VERSION 3.20)
project(GameScripts LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Engine paths
set(ERUPTION_INCLUDE_PATH ")" << engine_include << R"(")
set(ERUPTION_BUILD_PATH ")" << engine_build << R"(")

# Collect all script sources from project Assets folder
file(GLOB_RECURSE SCRIPT_SOURCES
    "${CMAKE_CURRENT_SOURCE_DIR}/../Assets/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../Assets/*.h"
)

# Also include default engine scripts from engine assets folder
file(GLOB_RECURSE ENGINE_SCRIPT_SOURCES
    "${ERUPTION_INCLUDE_PATH}/../assets/*.cpp"
    "${ERUPTION_INCLUDE_PATH}/../assets/*.h"
)
list(APPEND SCRIPT_SOURCES ${ENGINE_SCRIPT_SOURCES})

# Also include the script registry
list(APPEND SCRIPT_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/ScriptRegistry.cpp")

# ImGui sources (core only - needed for on_inspector_gui in scripts)
set(IMGUI_DIR "${ERUPTION_BUILD_PATH}/_deps/imgui-src")
list(APPEND SCRIPT_SOURCES
    "${IMGUI_DIR}/imgui.cpp"
    "${IMGUI_DIR}/imgui_draw.cpp"
    "${IMGUI_DIR}/imgui_tables.cpp"
    "${IMGUI_DIR}/imgui_widgets.cpp"
)

# Build as shared library (DLL)
add_library(GameScripts SHARED ${SCRIPT_SOURCES})

target_include_directories(GameScripts PRIVATE
    ${ERUPTION_INCLUDE_PATH}
    ${ERUPTION_BUILD_PATH}/_deps/entt-src/src
    ${ERUPTION_BUILD_PATH}/_deps/nlohmann_json-src/include
    ${IMGUI_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/../Assets
    ${ERUPTION_INCLUDE_PATH}/../assets
)

# Export symbols
target_compile_definitions(GameScripts PRIVATE BUILDING_GAME_SCRIPTS)

# Output to Library/ScriptAssemblies
set_target_properties(GameScripts PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
)

# Platform-specific settings
if(WIN32)
    # Windows: output to same directory for all configs
    set_target_properties(GameScripts PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    )
else()
    # Linux/macOS: Set visibility to hidden by default, explicit exports only
    set_target_properties(GameScripts PROPERTIES
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON
    )
endif()
)";

    cmake_file.close();

    // Always regenerate ScriptRegistry.cpp (it's fully auto-generated)
    std::string registry_path = (fs::path(m_scripts_path) / "ScriptRegistry.cpp").string();
    {
        std::ofstream registry_file(registry_path);
        if (registry_file.is_open()) {
            registry_file << R"(// Auto-generated by Eruption Editor - DO NOT EDIT
// Scripts register themselves via REGISTER_COMPONENT_SCRIPT() in their .cpp files.

#include "runtime/ComponentScript.h"
#include "runtime/SystemScript.h"
#include <imgui.h>

// Cross-platform export macro
#ifdef _WIN32
    #define SCRIPT_EXPORT __declspec(dllexport)
#else
    #define SCRIPT_EXPORT __attribute__((visibility("default")))
#endif

// Shared library exports called by the editor's DLLManager
extern "C" {

SCRIPT_EXPORT int GetScriptCount() {
    return static_cast<int>(runtime::get_script_registry().size());
}

SCRIPT_EXPORT const char* GetScriptName(int index) {
    return runtime::get_script_registry()[index].name;
}

SCRIPT_EXPORT runtime::ScriptFactory GetScriptFactory(int index) {
    return runtime::get_script_registry()[index].factory;
}

// Set ImGui context from host application (editor).
// This ensures the shared library uses the same ImGui context as the editor.
SCRIPT_EXPORT void SetImGuiContext(ImGuiContext* ctx) {
    ImGui::SetCurrentContext(ctx);
}

} // extern "C"
)";
            registry_file.close();
        }
    }

    // Create output directory
    fs::create_directories(fs::path(m_project_path) / "Library" / "ScriptAssemblies");

    engine::Logger::instance().info("ScriptCompiler", "Generated CMakeLists.txt at: %s", cmake_path.c_str());
    return true;
}

void ScriptCompiler::start_build() {
    if (is_building()) {
        return; // Already building
    }

    m_status = BuildStatus::Configuring;
    m_build_output.clear();
    m_last_error.clear();

    m_build_future = std::async(std::launch::async, [this]() {
        return build_sync();
    });
}

void ScriptCompiler::update() {
    if (!m_build_future.valid()) {
        return;
    }

    // Check if build is complete
    if (m_build_future.wait_for(std::chrono::milliseconds(0)) == std::future_status::ready) {
        bool success = m_build_future.get();

        if (m_build_complete_callback) {
            m_build_complete_callback(success);
        }
    }
}

bool ScriptCompiler::build_sync() {
    // Generate CMake files
    if (!generate_cmake()) {
        m_status = BuildStatus::Failed;
        return false;
    }

    // Create build directory
    fs::create_directories(m_build_path);

    // Configure
    m_status = BuildStatus::Configuring;
    if (!run_cmake_configure()) {
        if (!m_build_output.empty()) {
            engine::Logger::instance().error("ScriptCompiler", "Configure output:\n%s", m_build_output.c_str());
        }
        m_status = BuildStatus::Failed;
        return false;
    }

    // Build
    m_status = BuildStatus::Building;
    if (!run_cmake_build()) {
        if (!m_build_output.empty()) {
            engine::Logger::instance().error("ScriptCompiler", "Build output:\n%s", m_build_output.c_str());
        }
        m_status = BuildStatus::Failed;
        return false;
    }

    m_status = BuildStatus::Success;
    engine::Logger::instance().info("ScriptCompiler", "Build completed successfully");
    return true;
}

std::string ScriptCompiler::find_cmake() const {
    // Return cached path if already found
    if (!m_cmake_path.empty()) {
        return m_cmake_path;
    }

    // Use platform utility for cross-platform CMake discovery
    m_cmake_path = engine::platform::find_cmake();

    if (!m_cmake_path.empty()) {
        engine::Logger::instance().info("ScriptCompiler", "Found CMake at: %s", m_cmake_path.c_str());
    }

    return m_cmake_path;
}

bool ScriptCompiler::run_cmake_configure() {
    std::string cmake_exe = find_cmake();
    if (cmake_exe.empty()) {
        m_last_error = "CMake not found. To fix this:\n"
                       "  1. Place CMake in: tools/cmake/bin/cmake.exe (relative to editor)\n"
                       "  2. Or install CMake from: https://cmake.org/download/\n"
                       "  3. Or install Visual Studio with C++ CMake tools";
        engine::Logger::instance().error("ScriptCompiler", "CMake not found!");
        engine::Logger::instance().error("ScriptCompiler", "  Option 1: Place CMake in tools/cmake/bin/cmake.exe");
        engine::Logger::instance().error("ScriptCompiler", "  Option 2: Install from https://cmake.org/download/");
        engine::Logger::instance().error("ScriptCompiler", "  Option 3: Install Visual Studio with C++ CMake tools");
        return false;
    }

    // Build command with arguments
    std::vector<std::string> args;
    args.push_back("-S");
    args.push_back(m_scripts_path);
    args.push_back("-B");
    args.push_back(m_build_path);

#ifdef _WIN32
    // Use x64 architecture on Windows
    args.push_back("-A");
    args.push_back("x64");
#endif

    engine::Logger::instance().info("ScriptCompiler", "Running CMake configure...");

    auto result = m_process_runner->run_sync(cmake_exe, args, SUBPROCESS_TIMEOUT_MS);

    // Capture output
    if (!result.stdout_output.empty()) {
        m_build_output += result.stdout_output;
    }
    if (!result.stderr_output.empty()) {
        m_build_output += result.stderr_output;
    }

    if (result.timed_out) {
        m_last_error = "CMake configure timed out after " + std::to_string(SUBPROCESS_TIMEOUT_MS / 1000) + " seconds";
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    if (result.launch_failed) {
        m_last_error = "Failed to launch CMake process";
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    if (result.exit_code != 0) {
        m_last_error = "CMake configure failed with code: " + std::to_string(result.exit_code);
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    return true;
}

bool ScriptCompiler::run_cmake_build() {
    std::string cmake_exe = find_cmake();
    if (cmake_exe.empty()) {
        m_last_error = "CMake not found";
        return false;
    }

    // Build config must match the editor's config to avoid CRT mismatch.
    // Debug/Release use different CRT with different STL memory layouts on MSVC.
#ifdef NDEBUG
    constexpr const char* build_config = "Release";
#else
    constexpr const char* build_config = "Debug";
#endif

    std::vector<std::string> args;
    args.push_back("--build");
    args.push_back(m_build_path);
    args.push_back("--config");
    args.push_back(build_config);

    engine::Logger::instance().info("ScriptCompiler", "Running CMake build (%s)...", build_config);

    auto result = m_process_runner->run_sync(cmake_exe, args, SUBPROCESS_TIMEOUT_MS);

    // Capture output
    if (!result.stdout_output.empty()) {
        m_build_output += result.stdout_output;
    }
    if (!result.stderr_output.empty()) {
        m_build_output += result.stderr_output;
    }

    if (result.timed_out) {
        m_last_error = "CMake build timed out after " + std::to_string(SUBPROCESS_TIMEOUT_MS / 1000) + " seconds";
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    if (result.launch_failed) {
        m_last_error = "Failed to launch CMake build process";
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    if (result.exit_code != 0) {
        m_last_error = "CMake build failed with code: " + std::to_string(result.exit_code);
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    return true;
}

}
