#include "ScriptCompiler.h"
#include "engine/core/Logger.h"

#include <fstream>
#include <sstream>
#include <filesystem>
#include <cstdlib>
#include <cstdio>
#include <array>
#include <vector>

#ifdef _WIN32
#include <windows.h>
#endif

namespace fs = std::filesystem;

namespace editor {

#ifdef _WIN32
/// Maximum time (ms) to wait for a cmake subprocess before killing it.
static constexpr DWORD SUBPROCESS_TIMEOUT_MS = 120000;  // 2 minutes

/// Run a command silently (no visible CMD window) and wait for completion.
/// Returns the process exit code, -1 on launch failure, or -2 on timeout.
static int run_command_hidden(const std::string& command, std::string& output) {
    SECURITY_ATTRIBUTES sa{};
    sa.nLength = sizeof(sa);
    sa.bInheritHandle = TRUE;

    // Create pipe for capturing stdout/stderr
    HANDLE read_pipe = nullptr;
    HANDLE write_pipe = nullptr;
    CreatePipe(&read_pipe, &write_pipe, &sa, 0);
    SetHandleInformation(read_pipe, HANDLE_FLAG_INHERIT, 0);

    STARTUPINFOA si{};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW | STARTF_USESTDHANDLES;
    si.wShowWindow = SW_HIDE;
    si.hStdOutput = write_pipe;
    si.hStdError = write_pipe;

    PROCESS_INFORMATION pi{};

    // CreateProcess needs a mutable command string
    std::vector<char> cmd_buf(command.begin(), command.end());
    cmd_buf.push_back('\0');

    BOOL ok = CreateProcessA(
        nullptr, cmd_buf.data(), nullptr, nullptr, TRUE,
        CREATE_NO_WINDOW, nullptr, nullptr, &si, &pi);

    CloseHandle(write_pipe);

    if (!ok) {
        CloseHandle(read_pipe);
        return -1;
    }

    // Read output from pipe
    output.clear();
    char buf[4096];
    DWORD bytes_read = 0;
    while (ReadFile(read_pipe, buf, sizeof(buf) - 1, &bytes_read, nullptr) && bytes_read > 0) {
        buf[bytes_read] = '\0';
        output += buf;
    }
    CloseHandle(read_pipe);

    DWORD wait_result = WaitForSingleObject(pi.hProcess, SUBPROCESS_TIMEOUT_MS);

    if (wait_result == WAIT_TIMEOUT) {
        engine::Logger::instance().error("ScriptCompiler",
            "Process timed out after %d seconds, terminating",
            SUBPROCESS_TIMEOUT_MS / 1000);
        TerminateProcess(pi.hProcess, 1);
        CloseHandle(pi.hProcess);
        CloseHandle(pi.hThread);
        return -2;
    }

    DWORD exit_code = 0;
    GetExitCodeProcess(pi.hProcess, &exit_code);

    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    return static_cast<int>(exit_code);
}
#endif

ScriptCompiler::ScriptCompiler() = default;

ScriptCompiler::~ScriptCompiler() {
    // Wait for any pending build
    if (m_build_future.valid()) {
        m_build_future.wait();
    }
}

void ScriptCompiler::set_project_path(const std::string& path) {
    m_project_path = path;
    m_scripts_path = (fs::path(path) / "Scripts").string();
    m_build_path = (fs::path(path) / "Library" / "ScriptBuild").string();
}

void ScriptCompiler::set_engine_include_path(const std::string& path) {
    m_engine_include_path = path;
}

void ScriptCompiler::set_engine_build_path(const std::string& path) {
    m_engine_build_path = path;
}

std::string ScriptCompiler::dll_path() const {
#ifdef _WIN32
    return (fs::path(m_project_path) / "Library" / "ScriptAssemblies" / "GameScripts.dll").string();
#else
    return (fs::path(m_project_path) / "Library" / "ScriptAssemblies" / "libGameScripts.so").string();
#endif
}

bool ScriptCompiler::generate_cmake() {
    if (m_project_path.empty() || m_engine_include_path.empty()) {
        m_last_error = "Project path or engine include path not set";
        return false;
    }

    // Create Scripts directory (for CMakeLists.txt and ScriptRegistry.cpp)
    fs::create_directories(m_scripts_path);

    // Generate CMakeLists.txt
    std::string cmake_path = (fs::path(m_scripts_path) / "CMakeLists.txt").string();
    std::ofstream cmake_file(cmake_path);

    if (!cmake_file.is_open()) {
        m_last_error = "Failed to create CMakeLists.txt";
        return false;
    }

    // Convert paths to use forward slashes for CMake
    std::string engine_include = m_engine_include_path;
    std::replace(engine_include.begin(), engine_include.end(), '\\', '/');

    std::string engine_build = m_engine_build_path;
    std::replace(engine_build.begin(), engine_build.end(), '\\', '/');

    cmake_file << R"(# Auto-generated by Eruption Editor - DO NOT EDIT
cmake_minimum_required(VERSION 3.20)
project(GameScripts LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Engine paths
set(ERUPTION_INCLUDE_PATH ")" << engine_include << R"(")
set(ERUPTION_BUILD_PATH ")" << engine_build << R"(")

# Collect all script sources from Assets folder
file(GLOB_RECURSE SCRIPT_SOURCES
    "${CMAKE_CURRENT_SOURCE_DIR}/../Assets/*.cpp"
    "${CMAKE_CURRENT_SOURCE_DIR}/../Assets/*.h"
)

# Also include the script registry
list(APPEND SCRIPT_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/ScriptRegistry.cpp")

# ImGui sources (core only - needed for on_inspector_gui in scripts)
set(IMGUI_DIR "${ERUPTION_BUILD_PATH}/_deps/imgui-src")
list(APPEND SCRIPT_SOURCES
    "${IMGUI_DIR}/imgui.cpp"
    "${IMGUI_DIR}/imgui_draw.cpp"
    "${IMGUI_DIR}/imgui_tables.cpp"
    "${IMGUI_DIR}/imgui_widgets.cpp"
)

# Build as shared library (DLL)
add_library(GameScripts SHARED ${SCRIPT_SOURCES})

target_include_directories(GameScripts PRIVATE
    ${ERUPTION_INCLUDE_PATH}
    ${ERUPTION_BUILD_PATH}/_deps/entt-src/src
    ${IMGUI_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}
    ${CMAKE_CURRENT_SOURCE_DIR}/../Assets
)

# Export symbols
target_compile_definitions(GameScripts PRIVATE BUILDING_GAME_SCRIPTS)

# Output to Library/ScriptAssemblies
set_target_properties(GameScripts PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
)

# Windows-specific: output to same directory for all configs
if(WIN32)
    set_target_properties(GameScripts PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_RELWITHDEBINFO "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
        RUNTIME_OUTPUT_DIRECTORY_MINSIZEREL "${CMAKE_CURRENT_SOURCE_DIR}/../Library/ScriptAssemblies"
    )
endif()
)";

    cmake_file.close();

    // Always regenerate ScriptRegistry.cpp (it's fully auto-generated)
    std::string registry_path = (fs::path(m_scripts_path) / "ScriptRegistry.cpp").string();
    {
        std::ofstream registry_file(registry_path);
        if (registry_file.is_open()) {
            registry_file << R"(// Auto-generated by Eruption Editor - DO NOT EDIT
// Scripts register themselves via REGISTER_COMPONENT_SCRIPT() in their .cpp files.

#include "runtime/ComponentScript.h"
#include "runtime/SystemScript.h"
#include <imgui.h>

// DLL exports called by the editor's DLLManager
extern "C" {

#ifdef _WIN32
    __declspec(dllexport)
#endif
int GetScriptCount() {
    return static_cast<int>(runtime::get_script_registry().size());
}

#ifdef _WIN32
    __declspec(dllexport)
#endif
const char* GetScriptName(int index) {
    return runtime::get_script_registry()[index].name;
}

#ifdef _WIN32
    __declspec(dllexport)
#endif
runtime::ScriptFactory GetScriptFactory(int index) {
    return runtime::get_script_registry()[index].factory;
}

// Set ImGui context from host application (editor).
// This ensures the DLL uses the same ImGui context as the editor.
#ifdef _WIN32
    __declspec(dllexport)
#endif
void SetImGuiContext(ImGuiContext* ctx) {
    ImGui::SetCurrentContext(ctx);
}

} // extern "C"
)";
            registry_file.close();
        }
    }

    // Create output directory
    fs::create_directories(fs::path(m_project_path) / "Library" / "ScriptAssemblies");

    engine::Logger::instance().info("ScriptCompiler", "Generated CMakeLists.txt at: %s", cmake_path.c_str());
    return true;
}

void ScriptCompiler::start_build() {
    if (is_building()) {
        return; // Already building
    }

    m_status = BuildStatus::Configuring;
    m_build_output.clear();
    m_last_error.clear();

    m_build_future = std::async(std::launch::async, [this]() {
        return build_sync();
    });
}

void ScriptCompiler::update() {
    if (!m_build_future.valid()) {
        return;
    }

    // Check if build is complete
    if (m_build_future.wait_for(std::chrono::milliseconds(0)) == std::future_status::ready) {
        bool success = m_build_future.get();

        if (m_build_complete_callback) {
            m_build_complete_callback(success);
        }
    }
}

bool ScriptCompiler::build_sync() {
    // Generate CMake files
    if (!generate_cmake()) {
        m_status = BuildStatus::Failed;
        return false;
    }

    // Create build directory
    fs::create_directories(m_build_path);

    // Configure
    m_status = BuildStatus::Configuring;
    if (!run_cmake_configure()) {
        if (!m_build_output.empty()) {
            engine::Logger::instance().error("ScriptCompiler", "Configure output:\n%s", m_build_output.c_str());
        }
        m_status = BuildStatus::Failed;
        return false;
    }

    // Build
    m_status = BuildStatus::Building;
    if (!run_cmake_build()) {
        if (!m_build_output.empty()) {
            engine::Logger::instance().error("ScriptCompiler", "Build output:\n%s", m_build_output.c_str());
        }
        m_status = BuildStatus::Failed;
        return false;
    }

    m_status = BuildStatus::Success;
    engine::Logger::instance().info("ScriptCompiler", "Build completed successfully");
    return true;
}

std::string ScriptCompiler::find_cmake() const {
    // Return cached path if already found
    if (!m_cmake_path.empty()) {
        return m_cmake_path;
    }

#ifdef _WIN32
    // First, check for bundled CMake relative to the editor executable
    // Structure: tools/cmake/bin/cmake.exe
    fs::path exe_dir = fs::current_path();
    fs::path bundled_cmake = exe_dir / "tools" / "cmake" / "bin" / "cmake.exe";
    if (fs::exists(bundled_cmake)) {
        m_cmake_path = bundled_cmake.string();
        engine::Logger::instance().info("ScriptCompiler", "Found bundled CMake at: %s", m_cmake_path.c_str());
        return m_cmake_path;
    }

    // Also check one level up (in case we're in Debug/Release subfolder)
    bundled_cmake = exe_dir.parent_path() / "tools" / "cmake" / "bin" / "cmake.exe";
    if (fs::exists(bundled_cmake)) {
        m_cmake_path = bundled_cmake.string();
        engine::Logger::instance().info("ScriptCompiler", "Found bundled CMake at: %s", m_cmake_path.c_str());
        return m_cmake_path;
    }

    // Fallback: Common CMake installation paths on Windows
    std::vector<std::string> search_paths = {
        "C:\\Program Files\\CMake\\bin\\cmake.exe",
        "C:\\Program Files (x86)\\CMake\\bin\\cmake.exe",
        "C:\\cmake\\bin\\cmake.exe",
    };

    // Also check Visual Studio installations
    const char* program_files = std::getenv("ProgramFiles");
    if (program_files) {
        // VS 2022 bundled CMake
        search_paths.push_back(std::string(program_files) +
            "\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe");
        search_paths.push_back(std::string(program_files) +
            "\\Microsoft Visual Studio\\2022\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe");
        search_paths.push_back(std::string(program_files) +
            "\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe");
    }

    for (const auto& path : search_paths) {
        if (fs::exists(path)) {
            m_cmake_path = path;
            engine::Logger::instance().info("ScriptCompiler", "Found system CMake at: %s", path.c_str());
            return m_cmake_path;
        }
    }

    // Try system PATH as fallback (using where command)
    std::array<char, 512> buffer;
    FILE* pipe = _popen("where cmake 2>nul", "r");
    if (pipe) {
        if (fgets(buffer.data(), static_cast<int>(buffer.size()), pipe) != nullptr) {
            std::string result = buffer.data();
            // Remove trailing newline
            while (!result.empty() && (result.back() == '\n' || result.back() == '\r')) {
                result.pop_back();
            }
            if (!result.empty() && fs::exists(result)) {
                m_cmake_path = result;
                _pclose(pipe);
                engine::Logger::instance().info("ScriptCompiler", "Found CMake in PATH: %s", result.c_str());
                return m_cmake_path;
            }
        }
        _pclose(pipe);
    }
#else
    // On Unix, try common paths or rely on PATH
    std::vector<std::string> search_paths = {
        "/usr/bin/cmake",
        "/usr/local/bin/cmake",
        "/opt/homebrew/bin/cmake",  // macOS Homebrew ARM
        "/usr/local/Cellar/cmake/bin/cmake"  // macOS Homebrew Intel
    };

    for (const auto& path : search_paths) {
        if (fs::exists(path)) {
            m_cmake_path = path;
            return m_cmake_path;
        }
    }

    // Fallback to just "cmake" and hope it's in PATH
    m_cmake_path = "cmake";
#endif

    // If nothing found, return empty
    return "";
}

bool ScriptCompiler::run_cmake_configure() {
    std::string cmake_exe = find_cmake();
    if (cmake_exe.empty()) {
        m_last_error = "CMake not found. To fix this:\n"
                       "  1. Place CMake in: tools/cmake/bin/cmake.exe (relative to editor)\n"
                       "  2. Or install CMake from: https://cmake.org/download/\n"
                       "  3. Or install Visual Studio with C++ CMake tools";
        engine::Logger::instance().error("ScriptCompiler", "CMake not found!");
        engine::Logger::instance().error("ScriptCompiler", "  Option 1: Place CMake in tools/cmake/bin/cmake.exe");
        engine::Logger::instance().error("ScriptCompiler", "  Option 2: Install from https://cmake.org/download/");
        engine::Logger::instance().error("ScriptCompiler", "  Option 3: Install Visual Studio with C++ CMake tools");
        return false;
    }

    std::string command;
#ifdef _WIN32
    // Don't specify -G generator: CMake 3.20+ auto-detects the newest
    // available Visual Studio (works with VS 2019, 2022, and future versions).
    command = "\"" + cmake_exe + "\" -S \"" + m_scripts_path + "\" -B \"" + m_build_path + "\"";
    command += " -A x64";
#else
    command = "\"" + cmake_exe + "\" -S \"" + m_scripts_path + "\" -B \"" + m_build_path + "\"";
#endif

    engine::Logger::instance().info("ScriptCompiler", "Running: %s", command.c_str());

#ifdef _WIN32
    std::string cmd_output;
    int result = run_command_hidden(command, cmd_output);
    if (!cmd_output.empty()) {
        m_build_output += cmd_output;
    }
#else
    int result = std::system(command.c_str());
#endif
    if (result != 0) {
        m_last_error = "CMake configure failed with code: " + std::to_string(result);
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    return true;
}

bool ScriptCompiler::run_cmake_build() {
    std::string cmake_exe = find_cmake();
    if (cmake_exe.empty()) {
        m_last_error = "CMake not found";
        return false;
    }

    // Build config must match the editor's config to avoid CRT mismatch.
    // Debug/Release use different CRT with different STL memory layouts on MSVC.
#ifdef NDEBUG
    constexpr const char* build_config = "Release";
#else
    constexpr const char* build_config = "Debug";
#endif

    std::string command;
    command = "\"" + cmake_exe + "\" --build \"" + m_build_path + "\" --config " + build_config;

    engine::Logger::instance().info("ScriptCompiler", "Running: %s", command.c_str());

#ifdef _WIN32
    std::string cmd_output;
    int result = run_command_hidden(command, cmd_output);
    if (!cmd_output.empty()) {
        m_build_output += cmd_output;
    }
#else
    int result = std::system(command.c_str());
#endif
    if (result != 0) {
        m_last_error = "CMake build failed with code: " + std::to_string(result);
        engine::Logger::instance().error("ScriptCompiler", "%s", m_last_error.c_str());
        return false;
    }

    return true;
}

} // namespace editor
